name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
          - { name: macOS, os: macos-latest, triple: x86_64-apple-darwin }
          - { name: Windows, os: windows-latest, triple: x86_64-pc-windows-msvc }
        version:
          - 1.34.0
          - stable
          - nightly

    name: ${{ matrix.version }} - ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.version }}
        shell: bash
        run: TOOLCHAIN=${{ matrix.version }} TARGET=${{ matrix.target.triple }} sh ./ci/install-rust.sh

      - name: Rustfmt check
        if: matrix.version == 'stable' && matrix.target.name == 'Linux'
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --all -- --nocapture
